# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/student_analysis.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cproto/student_analysis.proto\x12\x10student_analysis\"\x88\x01\n\x0ePredictRequest\x12\x16\n\x0evideo_learning\x18\x01 \x01(\x02\x12\x19\n\x11material_learning\x18\x02 \x01(\x02\x12\x1b\n\x13\x63hapter_study_count\x18\x03 \x01(\x05\x12\x12\n\ndiscussion\x18\x04 \x01(\x02\x12\x12\n\nattendance\x18\x05 \x01(\x02\"H\n\x0fPredictResponse\x12\r\n\x05grade\x18\x01 \x01(\t\x12\x12\n\ngrade_code\x18\x02 \x01(\x05\x12\x12\n\nconfidence\x18\x03 \x01(\x02\"\x12\n\x10ModelInfoRequest\"\xd3\x01\n\x11ModelInfoResponse\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x15\n\rmodel_version\x18\x02 \x01(\t\x12\x10\n\x08\x66\x65\x61tures\x18\x03 \x03(\t\x12L\n\rgrade_mapping\x18\x04 \x03(\x0b\x32\x35.student_analysis.ModelInfoResponse.GradeMappingEntry\x1a\x33\n\x11GradeMappingEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xc6\x01\n\x16StudentAnalysisService\x12S\n\x0cPredictGrade\x12 .student_analysis.PredictRequest\x1a!.student_analysis.PredictResponse\x12W\n\x0cGetModelInfo\x12\".student_analysis.ModelInfoRequest\x1a#.student_analysis.ModelInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.student_analysis_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MODELINFORESPONSE_GRADEMAPPINGENTRY']._options = None
  _globals['_MODELINFORESPONSE_GRADEMAPPINGENTRY']._serialized_options = b'8\001'
  _globals['_PREDICTREQUEST']._serialized_start=51
  _globals['_PREDICTREQUEST']._serialized_end=187
  _globals['_PREDICTRESPONSE']._serialized_start=189
  _globals['_PREDICTRESPONSE']._serialized_end=261
  _globals['_MODELINFOREQUEST']._serialized_start=263
  _globals['_MODELINFOREQUEST']._serialized_end=281
  _globals['_MODELINFORESPONSE']._serialized_start=284
  _globals['_MODELINFORESPONSE']._serialized_end=495
  _globals['_MODELINFORESPONSE_GRADEMAPPINGENTRY']._serialized_start=444
  _globals['_MODELINFORESPONSE_GRADEMAPPINGENTRY']._serialized_end=495
  _globals['_STUDENTANALYSISSERVICE']._serialized_start=498
  _globals['_STUDENTANALYSISSERVICE']._serialized_end=696
# @@protoc_insertion_point(module_scope)
