# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_gen.proto import student_analysis_pb2 as proto_dot_student__analysis__pb2


class StudentAnalysisServiceStub(object):
    """学生成绩预测服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictGrade = channel.unary_unary(
                '/student_analysis.StudentAnalysisService/PredictGrade',
                request_serializer=proto_dot_student__analysis__pb2.PredictRequest.SerializeToString,
                response_deserializer=proto_dot_student__analysis__pb2.PredictResponse.FromString,
                )
        self.GetModelInfo = channel.unary_unary(
                '/student_analysis.StudentAnalysisService/GetModelInfo',
                request_serializer=proto_dot_student__analysis__pb2.ModelInfoRequest.SerializeToString,
                response_deserializer=proto_dot_student__analysis__pb2.ModelInfoResponse.FromString,
                )


class StudentAnalysisServiceServicer(object):
    """学生成绩预测服务
    """

    def PredictGrade(self, request, context):
        """预测学生成绩
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """获取模型信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StudentAnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictGrade': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictGrade,
                    request_deserializer=proto_dot_student__analysis__pb2.PredictRequest.FromString,
                    response_serializer=proto_dot_student__analysis__pb2.PredictResponse.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=proto_dot_student__analysis__pb2.ModelInfoRequest.FromString,
                    response_serializer=proto_dot_student__analysis__pb2.ModelInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'student_analysis.StudentAnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StudentAnalysisService(object):
    """学生成绩预测服务
    """

    @staticmethod
    def PredictGrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/student_analysis.StudentAnalysisService/PredictGrade',
            proto_dot_student__analysis__pb2.PredictRequest.SerializeToString,
            proto_dot_student__analysis__pb2.PredictResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/student_analysis.StudentAnalysisService/GetModelInfo',
            proto_dot_student__analysis__pb2.ModelInfoRequest.SerializeToString,
            proto_dot_student__analysis__pb2.ModelInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
